
---
- name: Install Python
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install python3
      apt:
        name: python3

        state: present
      become: true
